# Generated by Django 4.2.1 on 2023-07-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
